-- The contents of this migration were previously already executed when it was named '002'.
-- To prevent 'Duplicate Column' errors, the raw SQL is commented out.
-- ALTER TABLE users ADD COLUMN is_verified TINYINT(1) DEFAULT 0 AFTER password_hash;
-- ALTER TABLE users ADD COLUMN verification_token VARCHAR(64) DEFAULT NULL AFTER is_verified;
-- UPDATE users SET is_verified = 1;
