ALTER TABLE client_telemetry 
ADD COLUMN page VARCHAR(100) NULL,
ADD COLUMN page_load_ms INT DEFAULT 0,
ADD COLUMN php_time_ms FLOAT DEFAULT 0,
ADD COLUMN php_memory_mb FLOAT DEFAULT 0,
ADD COLUMN identifier_full VARCHAR(255) NULL;