<?php
require_once dirname(__DIR__, 2) . '/core/getconn.php';
require_once dirname(__DIR__, 2) . '/models/MatchManager.php';

$gameId = $_GET['game_id'] ?? 0;
if (!$gameId) die("Game ID ontbreekt");

$matchManager = new MatchManager($pdo);
$matchData = $matchManager->getSelection($gameId);

if (empty($matchData)) {
    die("Kan selectie en format niet inladen voor game " . htmlspecialchars($gameId));
}

$format = $matchData['format'];
$doelmannen = $matchData['doelmannen'] ?? '';
$selectie = $matchData['selectie'] ?? '';

// Array van spelers bepalen
$gk_arr = array_filter(array_map('trim', explode(',', $doelmannen)));
$sel_arr = array_filter(array_map('trim', explode(',', $selectie)));
$squad = array_merge($gk_arr, $sel_arr);
$aantal = count($squad);
$gk_count = count($gk_arr);

// Zorg er voor dat we $search_format hebben (bv 8v8_1gk_4x15)
$search_format = $format;
if (strpos($format, 'gk') === false) {
    if (preg_match('/^(\d+v\d+)_(\d+x\d+.*)$/', $format, $matches)) {
        $search_format = $matches[1] . '_' . $gk_count . 'gk_' . $matches[2];
    }
}
$full_format = $search_format . "_" . $aantal . "sp";

// Aantal blokken en speelduur (in minutes!) extraheren
$nr_of_games = 4;
$game_duration_min = 15;
$sub_duration_min = 15;

if (preg_match('/_(\d+)x(\d+)(?:_([0-9.]+)min)?$/', $search_format, $m)) {
    $nr_of_games = (int)$m[1];
    $game_duration_min = (int)$m[2];
    $sub_duration_min = isset($m[3]) ? (float)$m[3] : $game_duration_min;
}

if (isset($_GET['sub_freq']) && is_numeric($_GET['sub_freq'])) {
    $sub_duration_min = (float)$_GET['sub_freq'];
}

$total_minutes = $nr_of_games * $game_duration_min;
$number_of_shifts = ceil($total_minutes / $sub_duration_min);

// Bepaal logische wissel-frequenties o.b.v. wedstrijdblok duur
$logical_dividers = [];
foreach ([1, 2, 3, 4] as $div) {
    if ($game_duration_min % $div === 0 || ($game_duration_min === 15 && $div === 2)) {
        $val = $game_duration_min / $div;
        $logical_dividers[(string)$val] = $val;
    }
}
rsort($logical_dividers);

// In the UI, the shifts will be generated by JS.
$player_info = $matchData['player_info'] ?? [];
$players_json = [];

// Volgorde parameter vastleggen (nodig voor save payload en API):
$volgorde = implode(',', $squad);

foreach ($squad as $idx => $pid) {
    $players_json[$pid] = [
        'id' => $pid,
        'sidx' => $idx,
        'name' => htmlspecialchars($player_info[$pid]['display_name'] ?? $player_info[$pid]['first_name'] ?? $pid),
        'is_gk' => ($idx < $gk_count)
    ];
}

// Fetch historical season stats for these exact players before this game
$teamId = $_SESSION['team_id'] ?? 0;
$gameDate = $matchData['game']['game_date'];
$seasonStatsData = $matchManager->getSeasonStatsForSelection($teamId, $gameDate, $squad);

// Map the DB PIDs to JS Sidx (array indices)
$seasonStatsJson = [];
foreach ($squad as $idx => $pid) {
    $st = $seasonStatsData[$pid] ?? ['played' => 0, 'bank' => 0, 'gk' => 0, 'available' => 0];
    // If user confirmed GK counts as played time: we use 'played' + 'gk' for total played.
    // However, game_playtime_logs `seconds_played` currently ALREADY INCLUDES gk time (as per syncGameLogs logic pos 1 counts as 'played').
    // So 'played' is the total field time.
    $seasonStatsJson[$idx] = [
        'histPlayed' => $st['played'],
        'histAvailable' => $st['available']
    ];
}

$page_title = "Bouw Schema Manueel";
require_once dirname(__DIR__, 2) . '/header.php';
?>
<style>
.pool-container { background: #f8f9fa; min-height: 400px; padding: 15px; border-radius: 8px; border: 1px solid #dee2e6; }
.pool-player { background: #0d6efd; color: white; padding: 10px; margin-bottom: 8px; border-radius: 6px; cursor: grab; text-align: center; font-weight: bold; border: 2px solid transparent; transition: all 0.2s;}
.pool-player.is-gk { background: #dc3545; opacity: 0.8;}
.pool-player.on-bench-priority { background: #ffc107 !important; color: #000; border-color: #d39e00; }
.pos-wrapper { background: #fff; border: 2px dashed #ccc; border-radius: 6px; min-height: 40px; display: flex; align-items: center; justify-content: center; position: relative; margin-bottom: 10px;}
.pos-wrapper[data-pos="bench"] { border-color: #ffc107; background: #fff8e1; }
.pos-badge { position: absolute; top: -10px; left: 5px; background: #6c757d; color: white; font-size: 0.6rem; padding: 2px 5px; border-radius: 8px; z-index: 2;}
.pos-wrapper .pool-player { margin-bottom: 0; width: 100%; border-radius: 4px; padding: 3px; font-size: 0.85rem; z-index: 1;}

.shift-block.locked { opacity: 0.6; filter: grayscale(50%); }
.shift-block.locked .card-body { pointer-events: none; }
.shift-block.locked .card-header { background: #e9ecef !important; }
</style>

<div class="container mt-4 mb-5 pb-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h2><i class="fa-solid fa-hammer text-warning me-2"></i>Manuele Opstelling (Builder)</h2>
            <div class="d-flex align-items-center gap-3">
                <span class="text-muted">Wedstrijd format: <?= $search_format ?></span>
                <div class="d-flex align-items-center bg-white border rounded px-2 py-1 shadow-sm">
                    <label class="small text-muted me-2 fw-bold text-nowrap"><i class="fa-solid fa-stopwatch me-1"></i>Wisselen om de:</label>
                    <select class="form-select form-select-sm border-0 fw-bold" style="background-color: transparent; width: auto;" onchange="if(confirm('Als je de wisselfrequentie wijzigt, wordt je huidige schema gereset. Doorgaan?')) window.location.href='?game_id=<?= $gameId ?>&sub_freq='+this.value">
                        <?php foreach($logical_dividers as $val): ?>
                            <option value="<?= $val ?>" <?= (string)$sub_duration_min === (string)$val ? 'selected' : '' ?>>
                                <?= $val ?> min <?= $val == $game_duration_min ? '(Niet wisselen)' : '' ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
        <div>
            <a href="/games/<?= $gameId ?>/lineup" class="btn btn-outline-secondary me-2"><i class="fa-solid fa-arrow-left"></i> Terug</a>
            <button class="btn btn-success" onclick="saveNewSchema()" id="btnSave" disabled><i class="fa-solid fa-floppy-disk me-1"></i> Opslaan</button>
        </div>
    </div>

    <div class="row">
        <!-- Sidebar Pool -->
        <div class="col-md-3">
            <div class="pool-container sticky-top" style="top: 20px;">
                <h5 class="mb-3 text-dark"><i class="fa-solid fa-users me-2"></i>Selectie Pool</h5>
                <div id="player-pool">
                    <!-- JS fills this initially -->
                </div>
                <hr>
                <h5 class="mb-3 text-dark mt-4"><i class="fa-solid fa-chart-line me-2"></i>Live Statistieken</h5>
                <div class="table-responsive bg-white rounded shadow-sm mb-3">
                    <table class="table table-sm table-hover mb-0" style="font-size: 0.85rem;">
                        <thead class="table-light">
                            <tr>
                                <th>Speler</th>
                                <th class="text-center">Match %</th>
                                <th class="text-center" title="Historiek + deze Match">Seizoen %</th>
                            </tr>
                        </thead>
                        <tbody id="live-stats-tbody">
                            <!-- JS fills this dynamically -->
                        </tbody>
                    </table>
                </div>
                
                <div class="mt-3">
                    <small class="text-muted"><i class="fa-solid fa-info-circle"></i> Spelers die recht hebben op speeltijd lichten geel op in de pool en worden on top gesorteerd!</small>
                </div>
            </div>
        </div>

        <!-- The Canvas -->
        <div class="col-md-9">
            <div class="row" id="shifts-canvas">
                <!-- JS generates shifts here -->
            </div>
        </div>
    </div>
</div>

<script>
// Data
const numShifts = <?= $number_of_shifts ?>;
const subDurationMin = <?= $sub_duration_min ?>;
const totalMinutes = <?= $total_minutes ?>;
const playerCount = <?= $aantal ?>;
const formatStr = "<?= $search_format ?>";
const playersMap = <?= json_encode($players_json) ?>;
const seasonStatsMap = <?= json_encode($seasonStatsJson) ?>;
const gameId = <?= $gameId ?>;
const volgordeStr = "<?= $volgorde ?>";
const gkCount = <?= $gk_count ?>;
const fixedGkId = <?= $gk_count === 1 ? json_encode((int)reset($gk_arr)) : 'null' ?>;

let playPositions = [1, 2, 4, 5, 7, 9, 10, 11];
if (formatStr.includes('5v5')) {
    playPositions = [1, 2, 4, 5, 9];
}
let numField = playPositions.length; 
let maxBench = playerCount - (numField); 

let shiftData = []; 
let globalPlayerStats = {}; 

for(let pid in playersMap) {
    globalPlayerStats[playersMap[pid].sidx] = { name: playersMap[pid].name, fieldMin: 0, benchMin: 0, priority: 0 };
}

function initBuilder() {
    let canvas = document.getElementById('shifts-canvas');
    let pool = document.getElementById('player-pool');
    
    // Fill initial pool
    for(let pid in playersMap) {
        if (fixedGkId !== null && parseInt(pid) === fixedGkId) continue;
        let p = playersMap[pid];
        let el = document.createElement('div');
        el.className = 'pool-player' + (p.is_gk ? ' is-gk' : '');
        el.setAttribute('draggable', 'true');
        el.setAttribute('data-sidx', p.sidx);
        el.innerHTML = p.name;
        
        bindDragEvents(el);
        pool.appendChild(el);
    }
    
    // Form shifts logic
    for(let i=0; i<numShifts; i++) {
        let shiftIdx = i;
        let gCounter = Math.floor((i * subDurationMin) / (<?= $game_duration_min ?>)) + 1;
        
        let initialLineup = {};
        if (fixedGkId !== null) {
            initialLineup[1] = playersMap[fixedGkId].sidx;
        }

        shiftData.push({ shift: shiftIdx, duration: subDurationMin*60, game_counter: gCounter, start: (i*subDurationMin) + ":00", lineup: initialLineup, bench: [] });
        
        let col = document.createElement('div');
        col.className = 'col-12 col-xxl-6 mb-4';

        let block = document.createElement('div');
        block.className = 'card h-100 shift-block ' + (i > 0 ? 'locked border-secondary' : 'border-primary');
        block.id = 'shift-' + i;
        
        let html = `
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="mb-0 text-dark">Speelblok ${i+1} <small class="text-muted fw-normal">(${subDurationMin} min)</small></h5>
                <span class="badge bg-secondary" id="counter-${i}">0 / ${playerCount}</span>
            </div>
            <div class="card-body bg-light">`;
            
        html += `
            <div class="row mx-0 px-2 py-3">
                 <div class="col-md-9 field-area">
                    <div class="row px-2">`;
                    
        // Definieer de visuele rijen per format
        let formationRows = [];
        if (formatStr.includes('5v5')) {
            formationRows = [ [9], [11, 7], [4], [1] ];
        } else if (formatStr.includes('11v11')) {
            formationRows = [ [11, 9, 7], [8, 10, 6], [5, 4, 3, 2], [1] ];
        } else {
            // Default 8v8
            formationRows = [ [11, 9, 7], [10], [5, 4, 2], [1] ];
        }

        formationRows.forEach(rowPositions => {
            let rowHtml = `<div class="d-flex justify-content-center w-100 mb-2">`;
            let hasBoxes = false;
            rowPositions.forEach(pos => {
                hasBoxes = true;
                
                let innerPlayer = '';
                let extraStyles = '';
                if (fixedGkId !== null && pos === 1) {
                    let sidx = playersMap[fixedGkId].sidx;
                    let pName = playersMap[fixedGkId].name;
                    innerPlayer = `<div class="pool-player shadow-sm is-gk locked" draggable="false" data-sidx="${sidx}" data-id="${fixedGkId}" style="pointer-events: none; opacity: 0.9;">${pName}</div>`;
                    extraStyles = ' border-color: #dc3545; background-color: #f8d7da;';
                }
                
                rowHtml += `<div class="px-1" style="flex: 1; max-width: 30%;"><div class="pos-wrapper shadow-sm" data-pos="${pos}" data-shift="${i}" style="${extraStyles}"><span class="pos-badge">Pos ${pos}</span>${innerPlayer}</div></div>`;
            });
            rowHtml += `</div>`;
            if (hasBoxes) html += rowHtml;
        });
        
        html += `   </div>
                 </div>
                 <div class="col-md-3 bench-area px-1">
                    <div class="row px-2">`;
        
        for(let b=0; b<maxBench; b++) {
            html += `<div class="col-12 px-1"><div class="pos-wrapper shadow-sm" data-pos="bench" data-shift="${i}"><span class="pos-badge bg-warning text-dark"><i class="fa-solid fa-bed"></i> Bank</span></div></div>`;
        }
        
        html += `   </div>
                 </div>
            </div>
            </div>
            <div class="card-footer bg-white text-end py-2">
                ${i > 0 ? `<button class="btn btn-sm btn-outline-danger btn-reset d-none me-2" onclick="resetBlock(${i})"><i class="fa-solid fa-arrow-left"></i> Wis & Naar Vorige</button>` : ''}
                <button class="btn btn-sm btn-primary btn-lock d-none" onclick="lockBlock(${i})">Vastzetten & Volgende <i class="fa-solid fa-arrow-right"></i></button>
                <button class="btn btn-sm btn-outline-warning btn-unlock d-none" onclick="unlockBlock(${i})"><i class="fa-solid fa-unlock"></i> Bewerk Vanaf Hier</button>
            </div>
            `;
            
        block.innerHTML = html;
        col.appendChild(block);
        canvas.appendChild(col);
        
        block.querySelectorAll('.pos-wrapper').forEach(pw => {
            pw.addEventListener('dragover', e => { e.preventDefault(); pw.style.borderColor = '#0d6efd'; });
            pw.addEventListener('dragleave', e => { pw.style.borderColor = ''; });
            pw.addEventListener('drop', e => handleDrop(e, pw));
        });
        
        if(i === 0) {
            pool.addEventListener('dragover', e => { e.preventDefault(); });
            pool.addEventListener('drop', e => handleDropToPool(e, pool));
        }
    }
}

let draggedEl = null;
function bindDragEvents(el) {
    el.addEventListener('dragstart', function(e) {
        draggedEl = this;
        setTimeout(() => this.classList.add('opacity-50'), 0);
    });
    el.addEventListener('dragend', function(e) {
        this.classList.remove('opacity-50');
        draggedEl = null;
    });
}

function handleDropToPool(e, pool) {
    e.preventDefault();
    if(!draggedEl) return;
    
    let pw = draggedEl.closest('.pos-wrapper');
    if(!pw) return;
    
    let shiftIdx = parseInt(pw.getAttribute('data-shift'));
    let block = document.getElementById('shift-' + shiftIdx);
    if(block.classList.contains('locked')) return;
    
    if(shiftIdx !== 0) return;
    
    pool.appendChild(draggedEl);
    updateShiftData(shiftIdx);
}

function handleDrop(e, dropZone) {
    e.preventDefault();
    dropZone.style.borderColor = '';
    
    if(!draggedEl) return;
    
    let targetShiftIdx = parseInt(dropZone.getAttribute('data-shift'));
    let currentBlock = document.getElementById('shift-' + targetShiftIdx);
    if(currentBlock.classList.contains('locked')) {
        return;
    }
    
    let sourceContainer = draggedEl.parentNode;
    let existingPlayer = dropZone.querySelector('.pool-player');
    if (existingPlayer) {
        sourceContainer.appendChild(existingPlayer);
        dropZone.appendChild(draggedEl);
    } else {
        dropZone.appendChild(draggedEl);
    }
    
    updateShiftData(targetShiftIdx);
}

function updateShiftData(shiftIdx) {
    let block = document.getElementById('shift-' + shiftIdx);
    let sData = shiftData[shiftIdx];
    sData.lineup = {};
    if (fixedGkId !== null) sData.lineup[1] = playersMap[fixedGkId].sidx;
    sData.bench = [];
    
    let playerCountInBlock = 0;
    
    block.querySelectorAll('.pos-wrapper').forEach(pw => {
        let playerEl = pw.querySelector('.pool-player');
        if(playerEl) {
            playerCountInBlock++;
            let pSidx = parseInt(playerEl.getAttribute('data-sidx'));
            let pos = pw.getAttribute('data-pos');
            if(pos === 'bench') {
                sData.bench.push(pSidx);
            } else {
                sData.lineup[pos] = pSidx;
            }
        }
    });
    
    updateCounter(shiftIdx);
    
    let btnLock = block.querySelector('.btn-lock');
    if(playerCountInBlock === playerCount) {
        btnLock.classList.remove('d-none');
    } else {
        btnLock.classList.add('d-none');
    }
}

function resetBlock(shiftIdx) {
    if(shiftIdx === 0) return;
    
    let currentBlock = document.getElementById('shift-' + shiftIdx);
    
    // Clear non-fixed players
    currentBlock.querySelectorAll('.pool-player').forEach(el => {
        if(!el.classList.contains('locked')) el.remove();
    });
    updateShiftData(shiftIdx);
    
    // Make current locked again visually (but as future block)
    currentBlock.classList.add('locked');
    currentBlock.classList.replace('border-primary', 'border-secondary');
    currentBlock.querySelector('.btn-lock').classList.add('d-none');
    if(currentBlock.querySelector('.btn-reset')) currentBlock.querySelector('.btn-reset').classList.add('d-none');
    
    // Unlock previous
    let prevIdx = shiftIdx - 1;
    let prevBlock = document.getElementById('shift-' + prevIdx);
    prevBlock.classList.remove('locked');
    prevBlock.classList.replace('border-success', 'border-primary');
    prevBlock.classList.replace('border-secondary', 'border-primary');
    prevBlock.querySelector('.btn-unlock').classList.add('d-none');
    prevBlock.querySelector('.btn-lock').classList.remove('d-none');
    if(prevBlock.querySelector('.btn-reset')) prevBlock.querySelector('.btn-reset').classList.remove('d-none');
    
    calculateStats();
    prevBlock.scrollIntoView({behavior: "smooth", block: "center"});
}

function lockBlock(shiftIdx) {
    let block = document.getElementById('shift-' + shiftIdx);
    block.classList.add('locked');
    block.classList.replace('border-primary', 'border-success');
    block.querySelector('.btn-lock').classList.add('d-none');
    if(block.querySelector('.btn-reset')) block.querySelector('.btn-reset').classList.add('d-none');
    block.querySelector('.btn-unlock').classList.remove('d-none');
    
    calculateStats();
    
    let nextShiftIdx = shiftIdx + 1;
    if(nextShiftIdx < numShifts) {
        let nextBlock = document.getElementById('shift-' + nextShiftIdx);
        nextBlock.classList.remove('locked');
        nextBlock.classList.replace('border-secondary', 'border-primary');
        nextBlock.querySelector('.btn-lock').classList.remove('d-none');
        if(nextBlock.querySelector('.btn-reset')) nextBlock.querySelector('.btn-reset').classList.remove('d-none');
        
        let currentSData = shiftData[shiftIdx];
        
        currentSData.bench.forEach((s, idx) => fillNextBlockPos(nextShiftIdx, 'bench', s, idx));
        Object.keys(currentSData.lineup).forEach(pos => {
            if (fixedGkId !== null && parseInt(pos) === 1) return;
            fillNextBlockPos(nextShiftIdx, pos, currentSData.lineup[pos], 0);
        });
        
        updateShiftData(nextShiftIdx);
        nextBlock.scrollIntoView({behavior: "smooth", block: "center"});
    } else {
        document.getElementById('btnSave').disabled = false;
        alert("Alle kwartjes zijn ingevuld! Je kan je theorie nu opslaan.");
    }
}

function unlockBlock(shiftIdx) {
    if(!confirm("Waarschuwing: Alle blokken na deze blok worden gereset. Ben je zeker?")) return;
    
    let currentBlock = document.getElementById('shift-' + shiftIdx);
    currentBlock.classList.remove('locked');
    currentBlock.classList.replace('border-success', 'border-primary');
    currentBlock.querySelector('.btn-unlock').classList.add('d-none');
    currentBlock.querySelector('.btn-lock').classList.remove('d-none');
    if(currentBlock.querySelector('.btn-reset')) currentBlock.querySelector('.btn-reset').classList.remove('d-none');
    
    document.getElementById('btnSave').disabled = true;
    
    for(let i = shiftIdx + 1; i < numShifts; i++) {
        let laterBlock = document.getElementById('shift-' + i);
        laterBlock.classList.add('locked');
        laterBlock.classList.replace('border-primary', 'border-secondary');
        laterBlock.classList.replace('border-success', 'border-secondary');
        laterBlock.querySelector('.btn-unlock').classList.add('d-none');
        laterBlock.querySelector('.btn-lock').classList.add('d-none');
        if(laterBlock.querySelector('.btn-reset')) laterBlock.querySelector('.btn-reset').classList.add('d-none');
        
        laterBlock.querySelectorAll('.pool-player').forEach(el => {
            if(!el.classList.contains('locked')) el.remove();
        });
        updateShiftData(i);
    }
    calculateStats();
}

function fillNextBlockPos(targetShiftIdx, pos, sidx, benchIdx) {
    let container;
    if(pos === 'bench') {
        container = document.querySelectorAll(`#shift-${targetShiftIdx} .pos-wrapper[data-pos="bench"]`)[benchIdx];
    } else {
        container = document.querySelector(`#shift-${targetShiftIdx} .pos-wrapper[data-pos="${pos}"]`);
    }
    if(container) {
        let pName = "";
        let isGk = false;
        for(let pid in playersMap) {
            if(playersMap[pid].sidx == sidx) { pName = playersMap[pid].name; isGk = playersMap[pid].is_gk; }
        }
        
        let el = document.createElement('div');
        el.className = 'pool-player shadow-sm';
        el.setAttribute('draggable', 'true');
        el.setAttribute('data-sidx', sidx);
        
        let pStats = globalPlayerStats[sidx];
        if (pStats && pStats.benchMin > 0) {
            el.classList.add('on-bench-priority');
            el.innerText = pName + " ⏸ " + pStats.benchMin + "m";
        } else {
            el.innerText = pName + (isGk ? " (GK)" : "");
        }
        
        bindDragEvents(el);
        container.appendChild(el);
    }
}

function updateCounter(shiftIdx) {
    let block = document.getElementById('shift-' + shiftIdx);
    let count = block.querySelectorAll('.pool-player').length;
    let badge = document.getElementById('counter-' + shiftIdx);
    badge.innerText = count + " / " + playerCount;
    if(count === playerCount) {
        badge.classList.replace('bg-secondary', 'bg-success');
    } else {
        badge.classList.replace('bg-success', 'bg-secondary');
    }
}

function calculateStats() {
    // Reset priority
    for(let i in globalPlayerStats) {
        globalPlayerStats[i].priority = 0; globalPlayerStats[i].benchMin=0; globalPlayerStats[i].fieldMin=0;
    }
    // Calculate from locked shifts
    shiftData.forEach((sData, i) => {
        let block = document.getElementById('shift-' + i);
        if(block.classList.contains('locked')) {
            sData.bench.forEach(s => {
                globalPlayerStats[s].benchMin += (sData.duration / 60);
                globalPlayerStats[s].priority += 10;
            });
            Object.values(sData.lineup).forEach(s => {
                globalPlayerStats[s].fieldMin += (sData.duration / 60);
            });
        }
    });

    // Update pool visual sorting
    let pool = document.getElementById('player-pool');
    let poolItems = Array.from(pool.querySelectorAll('.pool-player'));
    poolItems.sort((a, b) => {
        let sidxA = parseInt(a.getAttribute('data-sidx'));
        let sidxB = parseInt(b.getAttribute('data-sidx'));
        let pA = globalPlayerStats[sidxA].priority;
        let pB = globalPlayerStats[sidxB].priority;
        return pB - pA; // Descending
    });
    
    poolItems.forEach(item => {
        let sidx = parseInt(item.getAttribute('data-sidx'));
        let pStats = globalPlayerStats[sidx];
        if (pStats.benchMin > 0) {
            item.classList.add('on-bench-priority');
            if(!item.innerText.includes('⏸')) {
                item.innerText = item.innerText + " ⏸ " + pStats.benchMin + "m";
            }
        } else {
            item.classList.remove('on-bench-priority');
        }
        pool.appendChild(item);
    });

    // Update Live Statistics Table
    let tbody = document.getElementById('live-stats-tbody');
    let statsHtml = '';
    
    // Convert globalPlayerStats to array to sort it alphabetically by name
    let statsArr = [];
    for(let i in globalPlayerStats) {
        statsArr.push({
            sidx: i,
            name: globalPlayerStats[i].name,
            fieldMin: globalPlayerStats[i].fieldMin,
            benchMin: globalPlayerStats[i].benchMin
        });
    }
    statsArr.sort((a, b) => a.name.localeCompare(b.name));

    // For total match time context, find the total duration of locked blocks
    let totalLockedMin = 0;
    shiftData.forEach((sData, i) => {
        if(document.getElementById('shift-' + i).classList.contains('locked')) {
            totalLockedMin += (sData.duration / 60);
        }
    });

    statsArr.forEach(st => {
        let matchPerc = 0;
        let matchAvailable = st.fieldMin + st.benchMin; // Time they are part of a locked block
        if(matchAvailable > 0) {
            matchPerc = (st.fieldMin / matchAvailable) * 100;
        }
        st.matchPerc = matchPerc;
        st.matchAvailable = matchAvailable;
    });

    statsArr.sort((a, b) => {
        // Sort by matchPerc ascending
        if (a.matchPerc !== b.matchPerc) return a.matchPerc - b.matchPerc;
        // Then by name
        return a.name.localeCompare(b.name);
    });

    statsArr.forEach(st => {
        let matchPercText = "0%";
        let matchColor = "text-muted";
        
        if(st.matchAvailable > 0) {
            matchPercText = Math.round(st.matchPerc) + "%";
            if (st.matchPerc < 50) matchColor = "text-danger fw-bold";
            else if (st.matchPerc >= 65) matchColor = "text-success fw-bold";
            else matchColor = "text-warning fw-bold";
        } else if (totalLockedMin > 0) {
            matchPercText = "-";
        }
        
        // Calculate Season totals
        let hist = seasonStatsMap[st.sidx];
        let totalSeasonPlayedSec = hist.histPlayed + (st.fieldMin * 60);
        let totalSeasonAvailableSec = hist.histAvailable + (matchAvailable * 60);
        
        let seasonPercText = "0%";
        let seasonColor = "text-muted";
        
        if (totalSeasonAvailableSec > 0) {
            let seasonPerc = (totalSeasonPlayedSec / totalSeasonAvailableSec) * 100;
            seasonPercText = Math.round(seasonPerc) + "%";
            
            if (seasonPerc < 50) seasonColor = "text-danger fw-bold";
            else if (seasonPerc >= 65) seasonColor = "text-success fw-bold";
            else seasonColor = "text-warning fw-bold";
        }
        
        statsHtml += `
            <tr>
                <td class="align-middle">${st.name}</td>
                <td class="text-center align-middle ${matchColor}">${matchPercText} <br><small class="text-muted fw-normal">${st.fieldMin}/${matchAvailable}m</small></td>
                <td class="text-center align-middle ${seasonColor}">${seasonPercText}</td>
            </tr>
        `;
    });
    
    tbody.innerHTML = statsHtml;
}

function saveNewSchema() {
    let btn = document.getElementById('btnSave');
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Ophalen...';
    btn.disabled = true;
    
    // Parse arrays correctly
    shiftData.forEach(sd => {
        sd.bench = sd.bench.map(s => parseInt(s));
        let fixedLineup = {};
        for(let pos in sd.lineup) { fixedLineup[pos] = parseInt(sd.lineup[pos]); }
        sd.lineup = fixedLineup;
    });

    fetch('api_save_schema.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            game_id: gameId,
            format: formatStr,
            aantal: playerCount,
            original_schema_id: 0,
            blocks: shiftData,
            volgorde: volgordeStr,
            force_settings_update: false,
            overwrite_mode: false
        })
    }).then(r => r.json()).then(data => {
        if(data.requires_confirm) {
            if(confirm(data.confirm_msg)) {
                submitForced();
            } else {
                btn.innerHTML = '<i class="fa-solid fa-floppy-disk me-1"></i> Opslaan';
                btn.disabled = false;
            }
        } else if(data.success) {
            alert("Nieuw Manueel Schema succesvol opgeslagen! We gaan nu naar de weergave.");
            if(data.is_duplicate) {
                alert("Tip: Je nieuwe theorie bestond toevallig reeds wiskundig (ID #" + data.new_id + ") en werd in de theorie gekoppeld!");
            }
            window.location.href = '/games/' + gameId + '/lineup?preview=' + data.lineup_id;
        } else {
            alert("Error: " + data.error);
            btn.innerHTML = '<i class="fa-solid fa-floppy-disk me-1"></i> Opslaan';
            btn.disabled = false;
        }
    }).catch(err => {
        alert("Server error");
        btn.disabled = false;
    });
}

function submitForced() {
    fetch('api_save_schema.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            game_id: gameId, format: formatStr, aantal: playerCount, original_schema_id: 0, blocks: shiftData, volgorde: volgordeStr, force_settings_update: true, overwrite_mode: false
        })
    }).then(r => r.json()).then(data => {
        if(data.success){
            window.location.href = '/games/' + gameId + '/lineup?preview=' + data.lineup_id;
        } else {
            alert("Error: "+data.error);
        }
    });
}

document.addEventListener('DOMContentLoaded', initBuilder);
</script>

<?php require_once dirname(__DIR__, 2) . '/footer.php'; ?>
