<?php
require_once 'getconn.php';
require_once 'MatchManager.php';

$gameId = $_GET['game_id'] ?? 0;
if (!$gameId) die("Game ID ontbreekt");

$matchManager = new MatchManager($pdo);
$matchData = $matchManager->getSelection($gameId);

if (empty($matchData)) {
    die("Kan selectie en format niet inladen voor game " . htmlspecialchars($gameId));
}

$format = $matchData['format'];
$doelmannen = $matchData['doelmannen'] ?? '';
$selectie = $matchData['selectie'] ?? '';

// Array van spelers bepalen
$gk_arr = array_filter(array_map('trim', explode(',', $doelmannen)));
$sel_arr = array_filter(array_map('trim', explode(',', $selectie)));
$squad = array_merge($gk_arr, $sel_arr);
$aantal = count($squad);
$gk_count = count($gk_arr);

// Zorg er voor dat we $search_format hebben (bv 8v8_1gk_4x15)
$search_format = $format;
if (strpos($format, 'gk') === false) {
    if (preg_match('/^(\d+v\d+)_(\d+x\d+.*)$/', $format, $matches)) {
        $search_format = $matches[1] . '_' . $gk_count . 'gk_' . $matches[2];
    }
}
$full_format = $search_format . "_" . $aantal . "sp";

// Aantal blokken en speelduur (in minutes!) extraheren
$nr_of_games = 4;
$game_duration_min = 15;
$sub_duration_min = 15;

if (preg_match('/_(\d+)x(\d+)(?:_(\d+)min)?$/', $search_format, $m)) {
    $nr_of_games = (int)$m[1];
    $game_duration_min = (int)$m[2];
    $sub_duration_min = isset($m[3]) ? (int)$m[3] : $game_duration_min;
}
$total_minutes = $nr_of_games * $game_duration_min;
$number_of_shifts = ceil($total_minutes / $sub_duration_min);

// In the UI, the shifts will be generated by JS.
$player_info = $matchData['player_info'] ?? [];
$players_json = [];

// Volgorde parameter vastleggen (nodig voor save payload en API):
$volgorde = implode(',', $squad);

foreach ($squad as $idx => $pid) {
    $players_json[$pid] = [
        'id' => $pid,
        'sidx' => $idx,
        'name' => htmlspecialchars($player_info[$pid]['display_name'] ?? $player_info[$pid]['first_name'] ?? $pid),
        'is_gk' => ($idx < $gk_count)
    ];
}

$page_title = "Bouw Schema Manueel";
require_once 'header.php';
?>
<style>
.pool-container { background: #f8f9fa; min-height: 400px; padding: 15px; border-radius: 8px; border: 1px solid #dee2e6; }
.pool-player { background: #0d6efd; color: white; padding: 10px; margin-bottom: 8px; border-radius: 6px; cursor: grab; text-align: center; font-weight: bold; border: 2px solid transparent; transition: all 0.2s;}
.pool-player.is-gk { background: #dc3545; opacity: 0.8;}
.pool-player.on-bench-priority { background: #ffc107 !important; color: #000; border-color: #d39e00; }
.pos-wrapper { background: #fff; border: 2px dashed #ccc; border-radius: 6px; min-height: 50px; display: flex; align-items: center; justify-content: center; position: relative; margin-bottom: 10px;}
.pos-wrapper[data-pos="bench"] { border-color: #ffc107; background: #fff8e1; }
.pos-badge { position: absolute; top: -10px; left: 10px; background: #6c757d; color: white; font-size: 0.7rem; padding: 2px 6px; border-radius: 10px; z-index: 2;}
.pos-wrapper .pool-player { margin-bottom: 0; width: 100%; border-radius: 4px; padding: 5px; z-index: 1;}

/* The block accordeon headers */
.shift-block.locked { opacity: 0.6; pointer-events: none; filter: grayscale(50%); }
.shift-block.locked .card-header { background: #e9ecef !important; }
</style>

<div class="container mt-4 mb-5 pb-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h2><i class="fa-solid fa-hammer text-warning me-2"></i>Manuele Opstelling (Builder)</h2>
            <p class="text-muted">Aantal Kwartjes: <?= $number_of_shifts ?> &middot; <?= $search_format ?></p>
        </div>
        <div>
            <a href="/games/<?= $gameId ?>/lineup" class="btn btn-outline-secondary me-2"><i class="fa-solid fa-arrow-left"></i> Terug</a>
            <button class="btn btn-success" onclick="saveNewSchema()" id="btnSave" disabled><i class="fa-solid fa-floppy-disk me-1"></i> Opslaan</button>
        </div>
    </div>

    <div class="row">
        <!-- Sidebar Pool -->
        <div class="col-md-3">
            <div class="pool-container sticky-top" style="top: 20px;">
                <h5 class="mb-3 text-dark"><i class="fa-solid fa-users me-2"></i>Selectie Pool</h5>
                <div id="player-pool">
                    <!-- JS fills this initially -->
                </div>
                <hr>
                <div class="mt-3">
                    <small class="text-muted"><i class="fa-solid fa-info-circle"></i> Spelers die recht hebben op speeltijd lichten geel op en worden on top gesorteerd!</small>
                </div>
            </div>
        </div>

        <!-- The Canvas -->
        <div class="col-md-9" id="shifts-canvas">
            <!-- JS generates shifts here -->
        </div>
    </div>
</div>

<script>
// Data
const numShifts = <?= $number_of_shifts ?>;
const subDurationMin = <?= $sub_duration_min ?>;
const playerCount = <?= $aantal ?>;
const formatStr = "<?= $search_format ?>";
const playersMap = <?= json_encode($players_json) ?>;
const gameId = <?= $gameId ?>;
const volgordeStr = "<?= $volgorde ?>";

let playPositions = [1, 2, 4, 5, 7, 9, 10, 11];
if (formatStr.includes('5v5')) {
    playPositions = [1, 2, 4, 5, 9];
}
let numField = playPositions.length - 1; // subtract gk
let maxBench = playerCount - (numField + 1); // e.g. 10 - 8 = 2

let shiftData = []; 
let globalPlayerStats = {}; 

for(let pid in playersMap) {
    globalPlayerStats[playersMap[pid].sidx] = { name: playersMap[pid].name, fieldMin: 0, benchMin: 0, priority: 0 };
}

function initBuilder() {
    let canvas = document.getElementById('shifts-canvas');
    let pool = document.getElementById('player-pool');
    
    // Fill initial pool
    for(let pid in playersMap) {
        let p = playersMap[pid];
        let el = document.createElement('div');
        el.className = 'pool-player' + (p.is_gk ? ' is-gk' : '');
        el.setAttribute('draggable', 'true');
        el.setAttribute('data-sidx', p.sidx);
        el.innerHTML = p.name + (p.is_gk ? ' (GK)' : '');
        
        bindDragEvents(el);
        pool.appendChild(el);
    }
    
    // Form shifts logic
    for(let i=0; i<numShifts; i++) {
        let shiftIdx = i;
        // Game counter: if 4x15, nr_of_games = 4, blocks = 4. 1x60 -> blocks = 4, game_counter = 1
        // Usually, format matches $nr_of_games. For 2x30_15min, counter should increment every 30 mins
        let gCounter = Math.floor((i * subDurationMin) / (<?= $game_duration_min ?>)) + 1;
        shiftData.push({ shift: shiftIdx, duration: subDurationMin*60, game_counter: gCounter, start: (i*subDurationMin) + ":00", lineup: {}, bench: [] });
        
        let block = document.createElement('div');
        block.className = 'card mb-4 shift-block ' + (i > 0 ? 'locked border-secondary' : 'border-primary');
        block.id = 'shift-' + i;
        
        let html = `
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="mb-0 text-dark">Speelblok ${i+1} <small class="text-muted fw-normal">(${subDurationMin} min)</small></h5>
                <span class="badge bg-secondary" id="counter-${i}">0 / ${playerCount}</span>
            </div>
            <div class="card-body row mx-0 px-2 py-3 bg-light">
                 <div class="col-md-9 field-area">
                    <h6 class="text-muted"><i class="fa-solid fa-people-group me-1"></i>Op Het Veld</h6>
                    <div class="row px-2">`;
                    
        playPositions.forEach(pos => {
            html += `<div class="col-4 col-sm-4 col-md-3 px-1"><div class="pos-wrapper shadow-sm" data-pos="${pos}" data-shift="${i}"><span class="pos-badge">Pos ${pos}</span></div></div>`;
        });            
        
        html += `   </div>
                 </div>
                 <div class="col-md-3 bench-area px-1">
                    <h6 class="text-muted"><i class="fa-solid fa-chair me-1"></i>Bank</h6>
                    <div class="row px-2">`;
        
        for(let b=0; b<maxBench; b++) {
            html += `<div class="col-12 px-1"><div class="pos-wrapper shadow-sm" data-pos="bench" data-shift="${i}"><span class="pos-badge bg-warning text-dark"><i class="fa-solid fa-bed"></i> Bank</span></div></div>`;
        }
        
        if(maxBench === 0) {
           html += `<div class="col-12"><small class="text-muted">Geen wissels</small></div>`;
        }
        
        html += `   </div>
                 </div>
            </div>
            <div class="card-footer bg-white text-end py-2">
                <button class="btn btn-sm btn-primary btn-lock d-none" onclick="lockBlock(${i})">Vastzetten & Volgende <i class="fa-solid fa-arrow-right"></i></button>
                <button class="btn btn-sm btn-outline-warning btn-unlock d-none" onclick="unlockBlock(${i})"><i class="fa-solid fa-unlock"></i> Ontgrendel</button>
            </div>
            `;
            
        block.innerHTML = html;
        canvas.appendChild(block);
        
        block.querySelectorAll('.pos-wrapper').forEach(pw => {
            pw.addEventListener('dragover', e => { e.preventDefault(); pw.style.borderColor = '#0d6efd'; });
            pw.addEventListener('dragleave', e => { pw.style.borderColor = ''; });
            pw.addEventListener('drop', e => handleDrop(e, pw));
        });
        
        // Also allow pool to accept drops back
        if(i === 0) {
            pool.addEventListener('dragover', e => { e.preventDefault(); });
            pool.addEventListener('drop', e => handleDropToPool(e, pool));
        }
    }
}

let draggedEl = null;
function bindDragEvents(el) {
    el.addEventListener('dragstart', function(e) {
        draggedEl = this;
        setTimeout(() => this.classList.add('opacity-50'), 0);
    });
    el.addEventListener('dragend', function(e) {
        this.classList.remove('opacity-50');
        draggedEl = null;
    });
}

function handleDropToPool(e, pool) {
    e.preventDefault();
    if(!draggedEl) return;
    
    // Only allow dropping back from the currently active shift (which is usually shift 0)
    let pw = draggedEl.closest('.pos-wrapper');
    if(!pw) return; // already in pool
    
    let shiftIdx = parseInt(pw.getAttribute('data-shift'));
    let block = document.getElementById('shift-' + shiftIdx);
    if(block.classList.contains('locked')) return;
    
    // We only support pool logic fully for shift 0 since shift 1 inherits auto
    if(shiftIdx !== 0) return;
    
    pool.appendChild(draggedEl);
    updateShiftData(shiftIdx);
}

function handleDrop(e, dropZone) {
    e.preventDefault();
    dropZone.style.borderColor = '';
    
    if(!draggedEl) return;
    
    let targetShiftIdx = parseInt(dropZone.getAttribute('data-shift'));
    let currentBlock = document.getElementById('shift-' + targetShiftIdx);
    if(currentBlock.classList.contains('locked')) {
        return;
    }
    
    let sourceContainer = draggedEl.parentNode;
    let sidx = draggedEl.getAttribute('data-sidx');
    let targetPos = dropZone.getAttribute('data-pos');
    
    // If dropping a GK
    if(draggedEl.classList.contains('is-gk')) {
        if(targetPos !== "1" && targetPos !== "bench") {
            alert("Een doelman mag enkel op positie 1 of op de bank staan!");
            return;
        }
    }
    
    let existingPlayer = dropZone.querySelector('.pool-player');
    if (existingPlayer) {
        if(existingPlayer.classList.contains('is-gk') && sourceContainer.id === 'player-pool') {
            alert("Je kan dit niet swappen"); return;
        }
        sourceContainer.appendChild(existingPlayer);
        dropZone.appendChild(draggedEl);
    } else {
        dropZone.appendChild(draggedEl);
    }
    
    updateShiftData(targetShiftIdx);
}

function updateShiftData(shiftIdx) {
    let block = document.getElementById('shift-' + shiftIdx);
    let sData = shiftData[shiftIdx];
    sData.lineup = {};
    sData.bench = [];
    
    let playerCountInBlock = 0;
    
    block.querySelectorAll('.pos-wrapper').forEach(pw => {
        let playerEl = pw.querySelector('.pool-player');
        if(playerEl) {
            playerCountInBlock++;
            let pSidx = parseInt(playerEl.getAttribute('data-sidx'));
            let pos = pw.getAttribute('data-pos');
            if(pos === 'bench') {
                sData.bench.push(pSidx);
            } else {
                sData.lineup[pos] = pSidx;
            }
        }
    });
    
    updateCounter(shiftIdx);
    
    let btnLock = block.querySelector('.btn-lock');
    if(playerCountInBlock === playerCount) {
        btnLock.classList.remove('d-none');
    } else {
        btnLock.classList.add('d-none');
    }
}

function lockBlock(shiftIdx) {
    let block = document.getElementById('shift-' + shiftIdx);
    block.classList.add('locked');
    block.classList.replace('border-primary', 'border-success');
    block.querySelector('.btn-lock').classList.add('d-none');
    block.querySelector('.btn-unlock').classList.remove('d-none');
    
    // Calculate Stats to sort Pool / Color Bench players
    calculateStats();
    
    let nextShiftIdx = shiftIdx + 1;
    if(nextShiftIdx < numShifts) {
        let nextBlock = document.getElementById('shift-' + nextShiftIdx);
        nextBlock.classList.remove('locked');
        nextBlock.classList.replace('border-secondary', 'border-primary');
        
        // Auto-fill next block by extracting exact state of current block!
        let currentSData = shiftData[shiftIdx];
        
        currentSData.bench.forEach((s, idx) => fillNextBlockPos(nextShiftIdx, 'bench', s, idx));
        Object.keys(currentSData.lineup).forEach(pos => {
            fillNextBlockPos(nextShiftIdx, pos, currentSData.lineup[pos], 0);
        });
        
        updateShiftData(nextShiftIdx);
        
        // Scroll to next
        nextBlock.scrollIntoView({behavior: "smooth", block: "center"});
    } else {
        // Validation / Complete Mode
        document.getElementById('btnSave').disabled = false;
        alert("Alle kwartjes zijn ingevuld! Je kan je theorie nu opslaan.");
    }
}

function unlockBlock(shiftIdx) {
    // You can only unlock if it's the last unlocked one in the chain,
    // Or you wipe all later! For simplicity: wiping later.
    if(!confirm("Waarschuwing: Alle blokken na deze blok worden gereset. Ben je zeker?")) return;
    
    let currentBlock = document.getElementById('shift-' + shiftIdx);
    currentBlock.classList.remove('locked', 'border-success');
    currentBlock.classList.add('border-primary');
    currentBlock.querySelector('.btn-lock').classList.remove('d-none');
    currentBlock.querySelector('.btn-unlock').classList.add('d-none');
    
    document.getElementById('btnSave').disabled = true;
    
    for(let i = shiftIdx + 1; i < numShifts; i++) {
        let laterBlock = document.getElementById('shift-' + i);
        laterBlock.classList.add('locked', 'border-secondary');
        laterBlock.classList.remove('border-primary', 'border-success');
        laterBlock.querySelector('.btn-unlock').classList.add('d-none');
        laterBlock.querySelector('.btn-lock').classList.add('d-none');
        // Clear them
        laterBlock.querySelectorAll('.pool-player').forEach(el => el.remove());
        updateShiftData(i);
    }
    calculateStats();
}

function fillNextBlockPos(targetShiftIdx, pos, sidx, benchIdx) {
    let container;
    if(pos === 'bench') {
        container = document.querySelectorAll(`#shift-${targetShiftIdx} .pos-wrapper[data-pos="bench"]`)[benchIdx];
    } else {
        container = document.querySelector(`#shift-${targetShiftIdx} .pos-wrapper[data-pos="${pos}"]`);
    }
    if(container) {
        let pName = "";
        let isGk = false;
        for(let pid in playersMap) {
            if(playersMap[pid].sidx == sidx) { pName = playersMap[pid].name; isGk = playersMap[pid].is_gk; }
        }
        
        let el = document.createElement('div');
        el.className = 'pool-player shadow-sm' + (isGk ? ' is-gk' : '');
        el.setAttribute('draggable', 'true');
        el.setAttribute('data-sidx', sidx);
        
        // Add visual hint if this player has bench priority!
        let pStats = globalPlayerStats[sidx];
        if (pStats && pStats.benchMin > 0) {
            el.classList.add('on-bench-priority');
            el.innerText = pName + " ⏸ " + pStats.benchMin + "m";
        } else {
            el.innerText = pName + (isGk ? " (GK)" : "");
        }
        
        bindDragEvents(el);
        container.appendChild(el);
    }
}

function updateCounter(shiftIdx) {
    let block = document.getElementById('shift-' + shiftIdx);
    let count = block.querySelectorAll('.pool-player').length;
    let badge = document.getElementById('counter-' + shiftIdx);
    badge.innerText = count + " / " + playerCount;
    if(count === playerCount) {
        badge.classList.replace('bg-secondary', 'bg-success');
    } else {
        badge.classList.replace('bg-success', 'bg-secondary');
    }
}

function calculateStats() {
    // Reset priority
    for(let i in globalPlayerStats) {
        globalPlayerStats[i].priority = 0; globalPlayerStats[i].benchMin=0; globalPlayerStats[i].fieldMin=0;
    }
    // Calculate from locked shifts
    shiftData.forEach((sData, i) => {
        let block = document.getElementById('shift-' + i);
        if(block.classList.contains('locked')) {
            sData.bench.forEach(s => {
                globalPlayerStats[s].benchMin += (sData.duration / 60);
                globalPlayerStats[s].priority += 10;
            });
            Object.values(sData.lineup).forEach(s => {
                globalPlayerStats[s].fieldMin += (sData.duration / 60);
            });
        }
    });

    // Update pool visual sorting
    let pool = document.getElementById('player-pool');
    let poolItems = Array.from(pool.querySelectorAll('.pool-player'));
    poolItems.sort((a, b) => {
        let sidxA = a.getAttribute('data-sidx');
        let sidxB = b.getAttribute('data-sidx');
        let pA = globalPlayerStats[sidxA].priority;
        let pB = globalPlayerStats[sidxB].priority;
        return pB - pA; // Descending (highest bench gets priority = upper in list)
    });
    
    poolItems.forEach(item => {
        let sidx = item.getAttribute('data-sidx');
        let pStats = globalPlayerStats[sidx];
        if (pStats.benchMin > 0) {
            item.classList.add('on-bench-priority');
            if(!item.innerText.includes('⏸')) {
                item.innerText = item.innerText + " ⏸ " + pStats.benchMin + "m";
            }
        } else {
            item.classList.remove('on-bench-priority');
        }
        pool.appendChild(item);
    });
}

function saveNewSchema() {
    let btn = document.getElementById('btnSave');
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Ophalen...';
    btn.disabled = true;
    
    // Parse arrays correctly
    shiftData.forEach(sd => {
        sd.bench = sd.bench.map(s => parseInt(s));
        let fixedLineup = {};
        for(let pos in sd.lineup) { fixedLineup[pos] = parseInt(sd.lineup[pos]); }
        sd.lineup = fixedLineup;
    });

    fetch('api_save_schema.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            game_id: gameId,
            format: formatStr,
            aantal: playerCount,
            original_schema_id: 0,
            blocks: shiftData,
            volgorde: volgordeStr,
            force_settings_update: false,
            overwrite_mode: false
        })
    }).then(r => r.json()).then(data => {
        if(data.requires_confirm) {
            if(confirm(data.confirm_msg)) {
                submitForced();
            } else {
                btn.innerHTML = '<i class="fa-solid fa-floppy-disk me-1"></i> Opslaan';
                btn.disabled = false;
            }
        } else if(data.success) {
            alert("Nieuw Manueel Schema succesvol opgeslagen! We gaan nu naar de weergave.");
            if(data.is_duplicate) {
                alert("Tip: Je nieuwe theorie bestond toevallig reeds wiskundig (ID #" + data.new_id + ") en werd in de theorie gekoppeld!");
            }
            window.location.href = '/games/' + gameId + '/lineup?preview=' + data.lineup_id;
        } else {
            alert("Error: " + data.error);
            btn.innerHTML = '<i class="fa-solid fa-floppy-disk me-1"></i> Opslaan';
            btn.disabled = false;
        }
    }).catch(err => {
        alert("Server error");
        btn.disabled = false;
    });
}

function submitForced() {
    fetch('api_save_schema.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            game_id: gameId, format: formatStr, aantal: playerCount, original_schema_id: 0, blocks: shiftData, volgorde: volgordeStr, force_settings_update: true, overwrite_mode: false
        })
    }).then(r => r.json()).then(data => {
        if(data.success){
            window.location.href = '/games/' + gameId + '/lineup?preview=' + data.lineup_id;
        } else {
            alert("Error: "+data.error);
        }
    });
}

document.addEventListener('DOMContentLoaded', initBuilder);
</script>

<?php require_once 'footer.php'; ?>
